[general]
mode          = "split1"
selection     = "random"
interval      = 300
collage_count = 4

[paths]
wallpapers_folder = "assets/wallpapers"
output_folder     = "assets/output"

[display]
fit_mode = "fill"
